import Head from "next/head";
import SideBar from "@/components/SideBar";
import Consultarquests from "@/components/Consultarquests";
import style from "@/styles/Home.module.css";



export default function quests() {
  return (
    <>
      <Head>
        <title>quests</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <div className = {style.wrapperFormulario}>
          <SideBar/>
            <main className ={style.formularioConsulta}>
            <Consultarquests/>
            </main>
        </div>
    </>
  );
}
